# Generated by Django 4.2.3 on 2023-07-08 09:05

import BaseUser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', BaseUser.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'مونث'), ('male', 'مذکر')], max_length=20, verbose_name='جنسیت'),
        ),
    ]
