# Generated by Django 4.2.3 on 2023-07-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0004_alter_user_avatar_alter_user_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outstandingaccesstoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlackListedAccessToken',
        ),
        migrations.DeleteModel(
            name='OutstandingAccessToken',
        ),
    ]
